### ISSUE TITLE
`scripts/routes.ts` script stopped working

### ISSUE THREAD

**Issue by ChrisVilches** [ChrisVilches/poller#12]
```sh
ts-node scripts/routes.ts
```

Output:

```
/home/felo/poller/scripts/runner.ts:11
    await callback(app);
          ^
TypeError: Cannot read properties of undefined (reading 'stack')
    at /home/felo/poller/scripts/routes.ts:8:38
    at bootstrap (/home/felo/poller/scripts/runner.ts:11:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ChrisVilches** [comment]
Scripts were removed because they are very unstable.
